libclod: include/clod/compression.h File Reference
compression.h File Reference
#include <clod/lib.h>
#include <stddef.h>
#include <stdint.h>
Macros
#define CLOD_COMPRESSION_DEFAULT_LEVEL INT8_MAX
#define CLOD_GZIP (1ull<<0)
#define CLOD_ZLIB (1ull<<1)
#define CLOD_DEFLATE (1ull<<2)
#define CLOD_LZ4 (1ull<<3)
#define CLOD_LZ4HC (1ull<<4)
#define CLOD_LZMA (1ull<<5)
#define CLOD_ZSTD (1ull<<6)
Enumerations
enum clod_compression_result {
CLOD_COMPRESSION_SUCCESS = 0 , CLOD_COMPRESSION_UNSUPPORTED = 1 , CLOD_COMPRESSION_MALFORMED = 2 , CLOD_COMPRESSION_SHORT_BUFFER = 3 ,
CLOD_COMPRESSION_SHORT_OUTPUT = 4 , CLOD_COMPRESSION_ALLOC_FAILED = 5
}
Functions
uint64_t clod_compression_support ()
struct clod_compressor * clod_compressor_init ()
void clod_compressor_free (struct clod_compressor *ctx)
enum clod_compression_result clod_compress (struct clod_compressor *ctx, void *dst, size_t dst_size, const void *src, size_t src_size, size_t *compressed_size, uint64_t algo, int8_t level)
struct clod_decompressor * clod_decompressor_init ()
void clod_decompressor_free (struct clod_decompressor *ctx)
enum clod_compression_result clod_decompress (struct clod_decompressor *ctx, void *dst, size_t dst_size, const void *src, size_t src_size, size_t *decompressed_size, uint64_t algo)
Macro Definition Documentation
CLOD_COMPRESSION_DEFAULT_LEVEL
#define CLOD_COMPRESSION_DEFAULT_LEVEL INT8_MAX
Definition at line 11 of file compression.h.
CLOD_GZIP
#define CLOD_GZIP (1ull<<0)
Definition at line 13 of file compression.h.
CLOD_ZLIB
#define CLOD_ZLIB (1ull<<1)
Definition at line 14 of file compression.h.
CLOD_DEFLATE
#define CLOD_DEFLATE (1ull<<2)
Definition at line 15 of file compression.h.
CLOD_LZ4
#define CLOD_LZ4 (1ull<<3)
Definition at line 16 of file compression.h.
CLOD_LZ4HC
#define CLOD_LZ4HC (1ull<<4)
Definition at line 17 of file compression.h.
CLOD_LZMA
#define CLOD_LZMA (1ull<<5)
Definition at line 18 of file compression.h.
CLOD_ZSTD
#define CLOD_ZSTD (1ull<<6)
Definition at line 19 of file compression.h.
Enumeration Type Documentation
clod_compression_result
enum clod_compression_result
Enumerator
CLOD_COMPRESSION_SUCCESS
The operation was successful.
CLOD_COMPRESSION_UNSUPPORTED
The specified algorithm isn't supported.
CLOD_COMPRESSION_MALFORMED
The compressed data is malformed.
CLOD_COMPRESSION_SHORT_BUFFER
The provided buffer is too short to hold the output.
CLOD_COMPRESSION_SHORT_OUTPUT
The output buffer is larger than the output, and bytes_written was null.
CLOD_COMPRESSION_ALLOC_FAILED
Allocation failed.
Definition at line 25 of file compression.h.
Function Documentation
clod_compression_support()
uint64_t clod_compression_support ()
Definition at line 4 of file compression.c.
clod_compressor_init()
struct clod_compressor * clod_compressor_init ()
Create a new compressor.
Returns
Newly allocated compressor, or nullptr on allocation failure.
Definition at line 27 of file compress.c.
References clod_compressor_init().
Referenced by clod_compressor_init().
clod_compressor_free()
void clod_compressor_free (struct clod_compressor * ctx)
Releases resources associated with the compressor.
Parameters
ctx Compressor to free.
Definition at line 33 of file compress.c.
References clod_compressor_free().
Referenced by clod_compressor_free().
clod_compress()
enum clod_compression_result clod_compress (struct clod_compressor * ctx, void * dst, size_t dst_size, const void * src, size_t src_size, size_t * compressed_size, uint64_t algo, int8_t level)
Compress data with a given compression algorithm.
Parameters
[in] ctx Compressor.
[in] dst Where compressed data is written.
[in] dst_size Size of dst.
[in] src Where data to be compressed is read from.
[in] src_size Size of src.
[out] compressed_size The actual size of the compressed output, or 0 if compression failed and the compressed size isn't known.
[in] algo The compression algorith to use.
[in] level Compression level to use. CLOD_COMPRESSION_DEFAULT_LEVEL will use the algos default.
Returns
Result of compression.
Exceptions
CLOD_COMPRESSION_SUCCESS on successful compression.
CLOD_COMPRESSION_UNSUPPORTED if the algo is unsupported.
CLOD_COMPRESSION_SHORT_BUFFER if the destination buffer is too small to hold the compressed output.
CLOD_COMPRESSION_ALLOC_FAILED if memory allocation failed.
Definition at line 62 of file compress.c.
References clod_compress(), CLOD_COMPRESSION_ALLOC_FAILED, CLOD_COMPRESSION_SHORT_OUTPUT, CLOD_COMPRESSION_SUCCESS, and CLOD_COMPRESSION_UNSUPPORTED.
Referenced by clod_compress().
clod_decompressor_init()
struct clod_decompressor * clod_decompressor_init ()
Create a new decompressor.
Returns
Newly allocated decompressor, or nullptr on allocation failure.
Definition at line 26 of file decompress.c.
References clod_decompressor_init().
Referenced by clod_decompressor_init().
clod_decompressor_free()
void clod_decompressor_free (struct clod_decompressor * ctx)
Release resources associated with the decompressor.
Parameters
ctx Decompressor to free.
Definition at line 32 of file decompress.c.
References clod_decompressor_free().
Referenced by clod_decompressor_free().
clod_decompress()
enum clod_compression_result clod_decompress (struct clod_decompressor * ctx, void * dst, size_t dst_size, const void * src, size_t src_size, size_t * decompressed_size, uint64_t algo)
Decompress some data with the given algorithm.
Parameters
ctx Decompressor.
dst Where uncompressed data is written.
dst_size Size of dst.
src Where compressed data is read from.
src_size Size of src.
decompressed_size The actual size of the uncompressed output, or 0 if decompression failed and the decompressed size isn't known.
algo The compression algorithm to use.
Returns
The result of the decompression.
Exceptions
CLOD_COMPRESSION_SUCCESS on successful decompression.
CLOD_COMPRESSION_UNSUPPORTED if the algo is unsupported.
CLOD_COMPRESSION_MALFORMED if the compressed data is malformed. THIS IS NOT AN INTEGRITY CHECK.
CLOD_COMPRESSION_SHORT_BUFFER if the destination buffer is too small to hold the decompressed output.
CLOD_COMPRESSION_SHORT_OUTPUT if dst is larger than the decompressed output and bytes_written is null.
CLOD_COMPRESSION_ALLOC_FAILED if memory allocation failed.
Definition at line 61 of file decompress.c.
References CLOD_COMPRESSION_ALLOC_FAILED, CLOD_COMPRESSION_MALFORMED, CLOD_COMPRESSION_SHORT_BUFFER, CLOD_COMPRESSION_SHORT_OUTPUT, CLOD_COMPRESSION_SUCCESS, CLOD_COMPRESSION_UNSUPPORTED, and clod_decompress().
Referenced by clod_decompress().