include_guard(GLOBAL)

set(BUILD_SHARED_LIBS_SAVED ${BUILD_SHARED_LIBS})
set(BUILD_STATIC_LIBS_SAVED ${BUILD_STATIC_LIBS})
set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ON)

set(CACHE{LIBDEFLATE_BUILD_GZIP} TYPE BOOL FORCE VALUE OFF)
set(CACHE{LIBDEFLATE_BUILD_TESTS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{LIBDEFLATE_BUILD_SHARED_LIB} TYPE BOOL FORCE VALUE OFF)
set(CACHE{LIBDEFLATE_BUILD_STATIC_LIB} TYPE BOOL FORCE VALUE ON)
add_subdirectory(
    "${CMAKE_CURRENT_SOURCE_DIR}/vendor/libdeflate"
    ${CMAKE_CURRENT_BINARY_DIR}/vendor/libdeflate
    EXCLUDE_FROM_ALL
)

set_target_properties(libdeflate_static PROPERTIES POSITION_INDEPENDENT_CODE ON)

set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE ${BUILD_SHARED_LIBS_SAVED})
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ${BUILD_STATIC_LIBS_SAVED})
