include_guard(GLOBAL)

set(BUILD_SHARED_LIBS_SAVED ${BUILD_SHARED_LIBS})
set(BUILD_STATIC_LIBS_SAVED ${BUILD_STATIC_LIBS})
set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ON)

set(CACHE{LZ4_POSITION_INDEPENDENT_LIB} TYPE BOOL FORCE VALUE ON)
set(CACHE{LZ4_BUNDLED_MODE} TYPE BOOL FORCE VALUE ON)
set(CACHE{LZ4_BUILD_CLI} TYPE BOOL FORCE VALUE OFF)
add_subdirectory(
    "${CMAKE_CURRENT_SOURCE_DIR}/vendor/lz4/build/cmake"
    ${CMAKE_CURRENT_BINARY_DIR}/vendor/lz4/cmake
    EXCLUDE_FROM_ALL
)

set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE ${BUILD_SHARED_LIBS_SAVED})
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ${BUILD_STATIC_LIBS_SAVED})
