include_guard(GLOBAL)

set(BUILD_TESTING_SAVED ${BUILD_TESTING})
set(BUILD_SHARED_LIBS_SAVED ${BUILD_SHARED_LIBS})
set(BUILD_STATIC_LIBS_SAVED ${BUILD_STATIC_LIBS})
set(CACHE{BUILD_TESTING} TYPE BOOL FORCE VALUE OFF)
set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ON)

set(CACHE{XZ_DOC} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_NLS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_THREADS} TYPE STRING FORCE VALUE "no")
set(CACHE{XZ_TOOL_LZMADEC} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_TOOL_LZMAINFO} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_TOOL_SCRIPTS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_TOOL_SYMLINKS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_TOOL_SYMLINKS_LZMA} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_TOOL_XZ} TYPE BOOL FORCE VALUE OFF)
set(CACHE{XZ_TOOL_XZDEC} TYPE BOOL FORCE VALUE OFF)
add_subdirectory(
    "${CMAKE_CURRENT_SOURCE_DIR}/vendor/xz"
    ${CMAKE_CURRENT_BINARY_DIR}/vendor/xz
    EXCLUDE_FROM_ALL
)

set_target_properties(liblzma PROPERTIES POSITION_INDEPENDENT_CODE ON)

set(CACHE{BUILD_TESTING} TYPE BOOL FORCE VALUE ${BUILD_TESTING_SAVED})
set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE ${BUILD_SHARED_LIBS_SAVED})
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ${BUILD_STATIC_LIBS_SAVED})
