include_guard(GLOBAL)

set(BUILD_SHARED_LIBS_SAVED ${BUILD_SHARED_LIBS})
set(BUILD_STATIC_LIBS_SAVED ${BUILD_STATIC_LIBS})
set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ON)

set(CACHE{ZSTD_BUILD_PROGRAMS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{ZSTD_BUILD_TESTS} TYPE BOOL FORCE VALUE OFF)
set(CACHE{ZSTD_LEGACY_SUPPORT} TYPE BOOL FORCE VALUE OFF)
set(CACHE{ZSTD_MULTITHREAD_SUPPORT} TYPE BOOL FORCE VALUE OFF)
set(CACHE{ZSTD_BUILD_SHARED} TYPE BOOL FORCE VALUE OFF)
set(CACHE{ZSTD_BUILD_STATIC} TYPE BOOL FORCE VALUE ON)
add_subdirectory(
    "${CMAKE_CURRENT_SOURCE_DIR}/vendor/zstd/build/cmake"
    ${CMAKE_CURRENT_BINARY_DIR}/vendor/zstd
    EXCLUDE_FROM_ALL
)

set_target_properties(libzstd_static PROPERTIES POSITION_INDEPENDENT_CODE ON)

set(CACHE{BUILD_SHARED_LIBS} TYPE BOOL FORCE VALUE ${BUILD_SHARED_LIBS_SAVED})
set(CACHE{BUILD_STATIC_LIBS} TYPE BOOL FORCE VALUE ${BUILD_STATIC_LIBS_SAVED})
